### ISSUE TITLE
Incorrect documentation for `ignite`

### ISSUE THREAD

**Issue by christopher-buss** [rbxts-flamework/core#106]
https://github.com/rbxts-flamework/core/blob/90e8134acd6bdfa48aab8a0500107f8b741704fa/src/flamework.ts#L196

Ignite's doc comments states that it returns the dependencies loaded, despite returning void. Either this jsdoc comment should not exist, or the ignite function should be changed to return the dependencies as stated.

**Comment by Fireboltofdeath** [comment]
Thank you for reporting this highly critical vulnerability.

Fixed in https://github.com/rbxts-flamework/core/commit/acf10f592881ae57e144e1cfb5edaa69b6b5da27
