### ISSUE TITLE
Inconsistent ID generation for .d.ts files

### ISSUE THREAD

**Issue by aidanborne** [rbxts-flamework/core#109]
Flamework's ID generation has differing behavior for `.d.ts` files depending on whether or not the file is a descendant of a `rootDir`.  `.d.ts` files that ARE a descendant of a `rootDir` (such as type declarations for `.lua` files or a `types.d.ts` file) won't have their extension removed, resulting in IDs like `@package/types.d.ts@MyInterface`. At the same time, `.d.ts` files that AREN'T a descendant of a `rootDir` will always have their extension removed, resulting in IDs like `@package/types@MyInterface`. This behavior discrepancy causes ID mismatches for packages that use declarations from `.d.ts` files.

**Package A**
```
// types.d.ts
export interface MyInterface {}
```
```
// .ts file
Flamework.id<MyInterface>() // @package/types.d.ts@MyInterface 
```
**Package B**
```
// .ts file (with MyInterface imported)
Flamework.id<MyInterface>() // @package/types@MyInterface 
```

**Comment by Fireboltofdeath** [comment]
Fixed in https://github.com/rbxts-flamework/transformer/commit/c455383c5ae5493cd921230b2e90bcfe2ed2f5e5
