### ISSUE TITLE
Network remoteEvent issue

### ISSUE THREAD

**Issue by lttzy** [rbxts-flamework/core#111]
shared/networt.ts
`import { Networking } from "@flamework/networking";`

`interface ClientToServerEvents {`
	`event(param1: string): void;`
`}`
`interface ServerToClientEvents {`
	`event(param1: string): void;`
}
`// Returns an object containing a `server` and `client` field.`
`export const GlobalEvents = Networking.createEvent<ClientToServerEvents, ServerToClientEvents>();`

server/services/example.ts
`import { GlobalEvents } from "shared/network";`
`GlobalEvents.event.fire()`
when I call GlobalEvents to fire, throw an error
Property 'event' does not exist on type 'GlobalEvent<ClientToServerEvents, ServerToClientEvents>'

**Comment by Fireboltofdeath** [comment]
Please refer to [the documentation](https://flamework.fireboltofdeath.dev/docs/additional-modules/networking/introduction#re-exporting).

There is also the [Flamework template](https://github.com/rbxts-flamework/template) which already has networking setup.
