### ISSUE TITLE
addPaths broken with multiplaces

### ISSUE THREAD

**Issue by pxky** [rbxts-flamework/core#112]
passing any path into addPaths throws an error during compilation if using a [multiplace](https://github.com/pxky/rbxts-multi-template) setup

![image](https://github.com/user-attachments/assets/7f0c5ce6-3a07-4392-8588-80dedc40083f)

**Comment by Fireboltofdeath** [comment]
Flamework doesn't support TypeScript's path aliases. You have to use the full path from your shared project root (I'm not sure exactly where this would be in multiplace projects, but it's probably your project directory)

**Comment by pxky** [comment]
![image](https://github.com/user-attachments/assets/085a3e30-b683-4725-a4b1-1ee3f1d15c0e)
full path works ✔️
