### ISSUE TITLE
instance guards with children are guranteed to fail on the client no matter what when an instance with a tag is added to workspace

### ISSUE THREAD

**Issue by Xuleos** [rbxts-flamework/core#17]
this issue addresses @flamework/components, but it doesn't seem to let me make issues over there.

When an object with a tag that is used for a component is parented to workspace on the server, it's pretty much guaranteed to fail any instance guard on the component just because there hasn't been a chance for the descendants to load in yet.

One potential solution is to just slap a `RunService.Heartbeat:Wait()` before doing anything when a tag is added to an object. This works perfectly when StreamingEnabled is off, but definitely wouldn't work otherwise. 

Could maybe just wait for all required children to get added before doing anything? but this might end up confusing the fuck out of people when a component instance never gets made for something without error because it has the wrong children

**Comment by Xuleos** [comment]
woo i beat my personal record for most confusing github issue

**Comment by Fireboltofdeath** [comment]
The only solution I can think of here is to run the guard on InstanceAdded and InstanceRemoved.. I'm not sure how much that'd affect performance, though, if you're constantly creating and removing instances inside a component. That may just have to be a drawback for consumers of the api, though.

**Comment by Fireboltofdeath** [comment]
https://github.com/rbxts-flamework/components/pull/1
