### ISSUE TITLE
Modding API

### ISSUE THREAD

**Issue by Fireboltofdeath** [rbxts-flamework/core#21]
all of the below are currently possible, using internal Flamework apis, but I'd like to expose a proper API for doing all of the above.

requesting feedback on potential use cases and what people would generally want this API to include

- custom lifecycle events
- custom decorators
- custom singletons

**Comment by Xuleos** [comment]
maybe not fully relevant to this, but can we have a way to add custom lifecycle events to components too? This might actually already be a thing and I just couldn't figure out how to do it lol

**Comment by Fireboltofdeath** [comment]
yep, that's not really possible currently..

the component system is separate from Flamework and components are created/removed arbitrarily, so the modding API will have to be able to account for that.

**Comment by Fireboltofdeath** [comment]
decorator metadata querying

Custom decorators may not always need all the metadata that Flamework provides, so they should be able to specify what will be generated at compile time

```ts
/**
  @Reflect design:paramtypes design:returntype guard:paramtypes guard:returntype
*/
declare const MyDecorator: Decorator;
```

**Comment by Fireboltofdeath** [comment]
https://github.com/rbxts-flamework/core/tree/modding-v2
https://github.com/rbxts-flamework/transformer/tree/modding-v2
https://github.com/rbxts-flamework/components/tree/modding-v2
