### ISSUE TITLE
Flamework error

### ISSUE THREAD

**Issue by returnSync** [rbxts-flamework/core#30]
Flamework wasn't compiling `Flamework.addPaths` correctly to Flamework._addPaths, and so I just updated flamework and it's transformer then now I'm back to getting this error:
`[Flamework]: Failed to load! TS version mismatch detected`
`[Flamework]: Flamework is using TypeScript version 4.5.2`
`Flamework]: roblox-ts requires TypeScript version 4.3.5`
`[Flamework]: You can fix this by setting your TypeScript version: npm install -D typescript@=4.3.5`
And this is pretty annoying because, back when I started this project I had to deal with this then I had to use the template and now I'm back to this again and it took so much of my time and I even did the suggestion to fix it but it didn't work.

**Comment by Zyrakia** [comment]
Do you happen to be using Yarn?

**Comment by returnSync** [comment]
No, I'm not also I fixed this issue.
