### ISSUE TITLE
Ability to add arbitrary instances into DI resolver

### ISSUE THREAD

**Issue by caneva20** [rbxts-flamework/core#36]
Hi!

It would be pretty handy to be able to register my own "instances" into the framework's DI container. I love working with DI, but I couldn't find a way to register a logger I usually use (`roblox-aurora/rbx-log`) to be used with flamework's DI system, it doesn't need to be anything fancy, something like this would do just fine:
```type-script
Flamework.addDependency(MY_DEPENDENCY_INSTANCE)
```

**Comment by Fireboltofdeath** [comment]
Currently, Flamework has an in-beta modding system (modding-v2 branch on relevant repositories, modding release on relevant npm packages) which allows you to specify custom decorators on classes which can then be resolved as singletons. Is this the behavior you desire, or do you specifically need to link an ID to a specific object for dependency injection?

**Comment by Fireboltofdeath** [comment]
This will be a feature in the new modding API https://github.com/rbxts-flamework/core/commit/70bdc654b38461fe2564361a53735370a0946805 which also includes other ways to augment dependency resolution (even completely overwriting Flamework's)

**Comment by caneva20** [comment]
Sorry for the way too late response.

I'll have a look at the modding API and check what can be done with it, based on your second reply it seems to be what I was looking for, I'll let you know, thanks!
