### ISSUE TITLE
Default attributes not set on component

### ISSUE THREAD

**Issue by hatmatty** [rbxts-flamework/core#47]
```typescript
import { OnStart } from "@flamework/core";
import { Component, BaseComponent } from "@flamework/components";

@Component({
	defaults: {
		attr: 1,
	},
})
export class component
	extends BaseComponent<{
		attr: number;
	}>
	implements OnStart
{
	onStart() {
		print(this.attributes.attr); // 1
		print(this.instance.GetAttribute("attr")); // nil
	}
}

```

**Comment by Zyrakia** [comment]
I believe this is intentional, modifying the attributes object will not result in any changes on the actual instance. In the documentation it says any invalid values will be substituted by the default value, not replaced.

**Comment by Fireboltofdeath** [comment]
As said by @Zyrakia, this is intentional behavior. I'm open to hearing use cases on why you want the defaults to be added onto the instance, though.

**Comment by hatmatty** [comment]
For instance let’s say you have a server-sided component that has a default attribute and is connected to a tag. On the client you might want to get that component’s instance by tag and see it’s default attribute. You could just set the default attributes by hand but this is just a bit of quality of life and I don’t think it would be too costly.

Also I might be missing something but @Zyrakia said “modifying the attributes object will not result in any changes on the actual instance“ but on the documentation it states “The attributes object on components is mutable, so you can change the value and it'll change in both the component's copy and on the instance.”

**Comment by jackTabsCode** [comment]
I agree, this behavior is both undefined and confusing. They should be synced IMO, otherwise the “attributes” name is misleading

**Comment by Fireboltofdeath** [comment]
https://github.com/rbxts-flamework/components/commit/2cee8e9dff00219890d25e117fae9804a485aa92
