### ISSUE TITLE
Transformer does not use specified Rojo project file given to rbxtsc

### ISSUE THREAD

**Issue by joritochip** [rbxts-flamework/core#53]
The roblox-ts CLI supports specifying a Rojo project file to use, but the flamework transformer does not respect this and instead will look for a default.project.json or, if there is no default.project.json, whichever it can find first.
![Code_9grhxyCTVh](https://user-images.githubusercontent.com/83682212/175833449-cb370b62-4e44-437c-a460-f2c0f6ca40f7.png)

**Comment by Fireboltofdeath** [comment]
https://github.com/rbxts-flamework/transformer/commit/103026cf6e01a2f285bc15252f189d359da45350
