### ISSUE TITLE
`@flamework/networking` and `@flamework/components` should not use tsconfig.json `"baseUrl"`

### ISSUE THREAD

**Issue by osyrisrblx** [rbxts-flamework/core#54]
`"baseUrl"` does not work inside of installed packages, so imports within type definition files can break.

For example: `node_modules/@flamework/networking/out/functions/types.d.ts`

![image](https://user-images.githubusercontent.com/9200592/176966572-1119279f-11c4-4a11-a82b-78fb0b4617a4.png)

**Comment by Fireboltofdeath** [comment]
https://github.com/rbxts-flamework/components/commit/dc40193b93f42f96f917fd2c5e4a1ce67c5320b1
https://github.com/rbxts-flamework/networking/commit/2038d998268a956330072a0bcc9841b57500f65d
