### ISSUE TITLE
Option to not generate client-side typechecking for remote events

### ISSUE THREAD

**Issue by safazi** [rbxts-flamework/core#75]
I know there is a parameter to bypass the type checking, but there should be an option to prevent the transformer from actually generating the types.

**Comment by Fireboltofdeath** [comment]
What's your use case?

**Comment by safazi** [comment]
I meant server->client remote functions, wrote the wrong thing. There should be an option for the transformer to not generate the return type checking - the client can trust that the server will return what it is supposed to.

**Comment by safazi** [comment]
Messed up again. I meant client -> server remote function invocation. Disabling the return guard is entirely viable (and I do that), but the server returns a big interface, and I'd rather it just not generate return type checking at all, especially as the interface gets larger and more complicated.

**Comment by Fireboltofdeath** [comment]
> Messed up again. I meant client -> server remote function invocation. Disabling the return guard is entirely viable (and I do that), but the server returns a big interface, and I'd rather it just not generate return type checking at all, especially as the interface gets larger and more complicated.

Is your issue for cosmetic reasons or are you having issues with the size of the interface?

**Comment by safazi** [comment]
Cosmetic and efficiency. I am of the opinion that the client does has no reason to validate the servers return data at all.

**Comment by Fireboltofdeath** [comment]
> Cosmetic and efficiency. I am of the opinion that the client does has no reason to validate the servers return data at all.

If guards are disabled on the client, it won't ever try to validate anything from the server.

I will take note of the cosmetic issues but that'll likely be addressed by #74 which won't inline the type guards

**Comment by Fireboltofdeath** [comment]
I am going to close this issue for now, if you think #74 isn't ideal for your use case then you can reopen but I believe it would solve the cosmetic issues you are concerned with.
