### ISSUE TITLE
Network batching

### ISSUE THREAD

**Issue by Fireboltofdeath** [rbxts-flamework/core#83]
Batch network requests per event.

It's also likely worth looking into running all events under a single remote (optionally)

**Comment by jackTabsCode** [comment]
I would imagine this would need to be configurable on a per-event basis.

**Comment by Fireboltofdeath** [comment]
I think I've decided against this for the time being as it can affect event ordering.

**Comment by Fireboltofdeath** [comment]
I think I've decided against this for the time being as it can affect event ordering.
