### ISSUE TITLE
Flamework macros not working inside decorators

### ISSUE THREAD

**Issue by lamborghinious** [rbxts-flamework/core#85]
Encountering an issue with the usage of a few macros within decorators. Specifically, the **Flamework.createGuard** and **Modding.inspect** macros do not seem to work properly when used inside decorators.

e.g. Modding.inspect<1>() results in Modding.inspect() in the output

Initially noticed this on version 20, but seems like it's also in version 21

**Comment by Fireboltofdeath** [comment]
https://github.com/rbxts-flamework/transformer/commit/00a34dedf1d2de737fc5965c137c1f2979fe05c8
