### ISSUE TITLE
Allow us to configure obsfucation separately for networking and singletons/components

### ISSUE THREAD

**Issue by jackTabsCode** [rbxts-flamework/core#86]
I enjoy Flamework's obfuscation feature for obscuring the names of our network events. However, when profiling the game in a live server, the microprofiler labels are nearly useless since these are also obfuscated.

**Comment by Fireboltofdeath** [comment]
These are already different features, networking generates random UUIDs whilst singletons identifiers are meant to uniquely identify a declaration.

Could you take a look to see if updating the `idGenerationMode` property is the desired behavior here?
https://fireboltofdeath.dev/blog/flamework/2022-05-15-release#id-generation

**Comment by jackTabsCode** [comment]
This is sufficient. Thank you!
