### ISSUE TITLE
support bun

### ISSUE THREAD

**Issue by Milo123459** [rbxts-flamework/core#97]
relevant discord message: [link](https://discord.com/channels/476080952636997633/1167835689115725976/1169750390217130004)

**Comment by Fireboltofdeath** [comment]
This should be fixed with the following commits.

https://github.com/rbxts-flamework/components/commit/ce4db01a33eff585d3c1e8cd3234271da21c135c
https://github.com/rbxts-flamework/networking/commit/67c7bcbfc7c04c4ad2fa175708d84f587d77e014
